name: Create Release

on:
  workflow_dispatch:

env:
  VERSION: '0.0.4'

jobs:
  run_batch_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Release Script
        run: |
          echo "Running shell script with version: $VERSION"
          mkdir release
          
          sed -i "s/\${version}/$VERSION/" ./chrome/manifest.json
          sed -i "s/\${version}/$VERSION/" ./tampermonkey/chess-helper.js
          
          cat ./chrome/manifest.json
          cat ./tampermonkey/chess-helper.js
          
          zip -r ./release/chess-helper.zip ./chrome
          cp ./tampermonkey/chess-helper.js ./release/chess-helper.js
          for asset in ./release/*; do
            md5sum $asset >> ./release/$asset.md5
            sha1sum $asset >> ./release/$asset.sha1
            sha256sum $asset >> ./release/$asset.sha256
            sha512sum $asset >> ./release/$asset.sha512
          done
          
          ls -l ./release

