name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Revised edition or updated version of the repository to be published.
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Release Script
        run: |
          echo "Running shell script with version: ${{ github.event.inputs.version }}"
          mkdir build
          
          sed -i "s/\${version}/${{ github.event.inputs.version }}/" ./chrome/manifest.json
          sed -i "s/\${version}/${{ github.event.inputs.version }}/" ./tampermonkey/chess-helper.js
          
          cat ./chrome/manifest.json
          cat ./tampermonkey/chess-helper.js
          
          zip -r ./build/chess-helper.zip ./chrome
          cp ./tampermonkey/chess-helper.js ./build/chess-helper.js
          for asset in ./build/*; do
            md5sum $asset >> $asset.md5
            sha1sum $asset >> $asset.sha1
            sha256sum $asset >> $asset.sha256
            sha512sum $asset >> $asset.sha512
          done
          
          ls -l ./build
      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.PERSONAL_TOKEN }}
          tag_name: v${{ github.event.inputs.version }}
          files: ./release