name: Create Release

on:
  workflow_dispatch:

env:
  VERSION: 0.0.4

jobs:
  run_batch_script:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Batch Script
        run: | 
          echo "Running batch script with version: $VERSION"
