name: Create Release

on:
  workflow_dispatch:

env:
  VERSION: ${{ inputs.version }}

jobs:
  run_batch_script:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Batch Script
        run: echo "Running batch script with version: $VERSION"

inputs:
  version:
    description: The version number to use in the script
    required: true
    default: "1.0.0"
